### ISSUE TITLE
Helm Tutorial Request

### ISSUE THREAD

**Issue by mattconger** [PrefectHQ/prefect-helm#157]
Requests for guided walk through of helm installation of getting a worker running for cloud.

Any step-by-step instructions would be greatly appreciated! Thanks

**Comment by MrCoffey** [comment]
Would be great to have instructions about how to configure an external instance of postgres.

**Comment by jmeisele** [comment]
> Would be great to have instructions about how to configure an external instance of postgres.

Does [this](https://github.com/PrefectHQ/prefect-helm/issues/127) closed issue help at all?

**Comment by parkedwards** [comment]
hey @MrCoffey - since this issue is about documenting the prefect-worker chart, feel free to create a new issue in this repo about what information you're looking for re: hooking into an external postgres instance (eg. which chart you're using, which parts are unclear) and we can look into documenting this use case

**Comment by MrCoffey** [comment]
Hey [jmeisele](https://github.com/jmeisele) yeah this [issue](https://github.com/PrefectHQ/prefect-helm/issues/127) helped me.
