### ISSUE TITLE
Interoperability of docker images

### ISSUE THREAD

**Issue by secrettoad** [PrefectHQ/prefect-helm#202]
Hi all,

I am wondering if the tini command and the entrypoint.sh are strictly necessary for this chart to function well. I ask because they prevent any other image with prefect installed on it from successfully being used with the chart without implementing those pieces as well. Would it be safe to remove these and rely on the "prefect agent start" command to run the agent?

**Comment by jawnsy** [comment]
Hey there! The reason we have `tini` is to handle reaping of subprocesses. You can remove it, but you may (or may not) have issues with zombie processes accumulating, especially if you are running flows in processes rather than Kubernetes jobs or similar.

Additionally, we don't do our own testing with running `prefect agent start` directly (without a init system like tini), so you may run into issues there. Because of this, if you encounter issues, we can review bug reports on a best-effort basis; the main caveat is that you'd be using a configuration that is not as well-tested, so you have to be willing to take on the risk of investigating bugs and the like.

That said, this chart was previously running `prefect agent start` without `tini` and, as far as we could tell, it worked fine, so it may continue to work well for you. However, the chart currently hard-codes the `tini` invocation, so we'd have to make a decision as to whether we want to support that configuration (or you'd have to fork this chart): https://github.com/PrefectHQ/prefect-helm/blob/95674f322c8aee126d9cd5affd27e6eac379ed62/charts/prefect-agent/templates/deployment.yaml#L58-L62
