### ISSUE TITLE
document unsupported feature sets moving forward, automation on issues

### ISSUE THREAD

**Issue by parkedwards** [PrefectHQ/prefect-helm#216]
- [ ] communicate which feature domains are no longer supported, in the repo's README.  describe rationale
- [ ] create separate `actions/stale` workflow, to look for a new `not doing` label (combine with the existing workflow if possible)

**Comment by jawnsy** [comment]
IMO, if it's stuff we're not planning to do, we can add a comment and just close out the issue as Not Planned. People can add comments to the issue, it'll still be searchable, and it'll still be reopenable later if we change our mind.

I think historically we've avoided closing things out and just ignoring the issue until the stale bot closed it out, which also seems fine to me (provided that others on the team know not to pick up that work)

If it's a valid issue but not a priority, then it would be fair to respond by saying that we'd review a pull request, but are not planning to implement this due to resource constraints on our side (also IMO a very reasonable response)

**Comment by parkedwards** [comment]
word, that works for me. closing this one
