### ISSUE TITLE
Errors caused by new default security settings

### ISSUE THREAD

**Issue by padbk** [PrefectHQ/prefect-helm#54]
Mainly finding these on the agent. Will update this issue as I come across them.

1. Error when executing a flow on the agent:
`FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/opt/prefect']`
Solved by changing the following from true to false: 
containerSecurityContext:
readOnlyRootFilesystem: false

2. Error when installing additional python packages on the agent:
`ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'`
`Check the permissions.`
Currently unsolved, but think it is due to the user id 1001 not existing in /etc/passwd

**Comment by jawnsy** [comment]
Hey there!

Thanks so much for reporting this issue.

I'm working on a fix for these, but in the meantime, I think you can work around the second issue by running the agent as root (`runAsUser: 0`); in combination with `readOnlyRootFilesystem: false`, it should make everything writable again, as before

**Comment by jawnsy** [comment]
Looking into this, I think there's a few related issues due to a misunderstanding on my part during the initial implementation.

* When running as user `1001`, the user is not in `/etc/passwd` so does not have a homedir, and defaults to `/` -- this means that trying to install packages using `pip install` as this user will attempt to write to `/.cache`
* I had assumed that `PREFECT_HOME` was an installation directory for Prefect and that the `.prefect` directory was a fixed subdirectory, but that is not the case -- it defaults to `HOME/.prefect` but allows the user to override the location: https://github.com/PrefectHQ/prefect/blob/5be9532d12c4942a7f35bfb7612108d2c6bda5a5/src/prefect/settings.py#L241-L247
* Rather than overriding PREFECT_HOME and mounting a writable directory there, we actually want to add a HOME environment variable

So I think the fix is to replace PREFECT_HOME with HOME and mount a writable directory there, which should fix unprivileged pip installs and give the orion server and agent our expected scratch space. I'll also add some documentation describing the different configurations we want according to our target environment.

I tested the orion server functionality locally using `podman run --rm -it --user 1001 -e HOME=/home/prefect --read-only -v /home/prefect prefecthq/prefect:2-latest /bin/bash` (replace podman with docker if you're using that) and everything started without error. I ran `prefect orion start` and also installed `pytest` locally, everything seems to work fine.

I'll test with the Helm install in an actual cluster tomorrow.

I'll also update our docs to describe the defaults and three different installation options:

* Running in OpenShift with the `restricted` SCC - in this case, runAsUser needs to be set to `null` to allow OpenShift to select a user
* Running unprivileged (the default)
* Running as root and allowing a writable filesystem -- this is the most compatible with the defaults we had previously, and also allows use of `apt` packages, but will conflict with locked-down clusters

cc @madkinsz @jamiezieziula @desertaxle
