### ISSUE TITLE
Setup permissions so that we can read the kube-system namespace to get its UID.

### ISSUE THREAD

**Issue by peytonrunyan** [PrefectHQ/prefect-helm#91]
Prefect uses the `kube-system` namespace to get the UID for job identification purpose. 

See the discussion here: https://prefect-community.slack.com/archives/CL09KU1K7/p1670585894619609?thread_ts=1670582075.035229&cid=CL09KU1K7

**Comment by jawnsy** [comment]
Cross-linking the issues for context: https://github.com/PrefectHQ/prefect/issues/7739 and https://github.com/PrefectHQ/prefect/pull/7747

A role binding to read namespaces is probably safe to add. With Kubernetes RBAC, the person creating role bindings needs to have at least the same permissions or greater (to prevent privilege escalation), and clusters in restricted environments often do not give people much access especially outside their current namespace.

OpenShift is one such restricted Kubernetes environment, but even so, I think they allow everyone to read all namespaces, so this is probably fine. An alternative might be to generate a token in Helm and store in a ConfigMap: https://github.com/PrefectHQ/prefect/issues/7739#issuecomment-1343801111

**Comment by madkinsz** [comment]
Unfortunately generating a token here won't help us solve this when deploying agents without Helm — which I believe is quite common. I'm happy to include a fallback if the UID cannot be retrieved, but I'm not sure what the best option for that is yet.

**Comment by madkinsz** [comment]
A user suggested an environment variable to override this behavior, I think `PREFECT_KUBERNETES_CLUSTER_UID` could be used first to support reduced permissions and then we can fallback to a read of the namespace. If we want, we can set this special environment variable in the Helm chart.

**Comment by jawnsy** [comment]
There will be two changes to support this:

1. We will add an environment variable (exact name TBD) to the Python code, which will take precedence over the Cluster UID detection. It will be configurable by changing extraEnvVars, but will not otherwise be configurable (i.e. it will not be in the Helm Values) https://github.com/PrefectHQ/prefect-helm/blob/2f63c923ffe1c9330c8731aa08a71ec521bca418/charts/prefect-agent/values.yaml#L121-L127
2. The default behavior will be to detect a cluster identifier, either at Helm installation time or runtime (exact approach is TBD; we'll likely have to experiment here)

There are two possible approaches to (2) that we can explore:

1. We can add a [ClusterRole and ClusterRoleBinding](https://github.com/bitnami/charts/blob/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml#L2) to have `get` permission on the `kube-system` namespace. This would be [gated with a `rbac.create` parameter](https://github.com/bitnami/charts/blob/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml#L1), so that restrictive clusters can prevent the creation of the bindings. This flag will also control whether namespaced Role/RoleBindings are created.

   If users want to manage RBAC settings themselves, they can set this to "false" and then manage RBAC separately from this chart. In this case, they are responsible for creating necessary Role, RoleBinding, ClusterRole, ClusterRoleBinding -- or they can request that a a cluster administrator handle that on their behalf.
1. Because the UID is immutable and only needs to be looked up once, we can potentially use the [Helm lookup command](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) during installation to read the `kube-system` UID during installation, and then inject that into the chart.

   This would mean that the service account would not need to read the kube-system namespace directly, and the user installing the chart would not need permission to create ClusterRole/ClusterRoleBindings; they only need permission to read the metadata for the kube-system namespace.

   A minor disadvantage of the `lookup` approach is that it will not work when performing a dry run.

I believe this should support all our known use cases/handle all known restrictions in a reasonable way.

**Comment by madkinsz** [comment]
Here's a PR for the environment variable: https://github.com/PrefectHQ/prefect/pull/7864

@hateyouinfinity — since most cluster names pulled from the config are not unique across machines, we are very hesitant to use that. It's likely to lead to incorrect reports of cancelled runs.
